### ISSUE TITLE
Deploy Project Assets to Google Storage for CDN

### ISSUE THREAD

**Issue by bhubbard** [wp-gulp/wp-gulp#4]
We want plugins and themes to load assets via a CDN for performance, when we release versions we should be using the CDN version of assets whenever possible, with fallback to local. 

https://www.npmjs.com/package/gulp-gcloud-publish
https://www.npmjs.com/package/gulp-gcloud

**Comment by sfgarza** [comment]
Issue is out of project scope. Moving issue into @imFORZA/imforza-cli
